Taira/components
Piko-Piko-Pon-Taro/navict-app pull request #159
Opened 2021-05-21 06:07 UTC by pahalce

RM作成まで(レコメンドとメモはまだやってないけどとりあえず一回なげる)#144

2021-05-21 06:43 UTC, dubianhaozhi requested changes

2021-05-21 06:43 UTC, dubianhaozhi commented on pages/test.tsx
> +import React, { useState } from 'react'
test.tsxページの差分いらない！

2021-05-21 06:43 UTC, dubianhaozhi commented on server/api/steps/recommended/index.ts
> +export type Methods = {
このファイルいらないので`server/api/steps/recommended/`フォルダごと削除してちょ

2021-05-21 06:43 UTC, dubianhaozhi commented on server/api/steps/recommended/controller.ts
> +import { defineController } from './$relay'
このファイルいらないので`server/api/steps/recommended/`フォルダごと削除してちょ

2021-05-21 06:43 UTC, dubianhaozhi commented on components/roadmaps/basicInfo/TagSelect.tsx
> +import { ControllerRenderProps, FieldValues } from 'react-hook-form'
このファイルいらなかったら消してちょ

2021-05-21 06:43 UTC, dubianhaozhi commented on components/roadmaps/step/LibrarySelect.tsx
> +import { ControllerRenderProps, FieldValues } from 'react-hook-form'
このファイルいらなかったら消してちょ

2021-05-21 06:43 UTC, dubianhaozhi commented on components/roadmaps/step/OpenStepForm.tsx
> +  children: React.ReactNode
これって、
このコンポーネント自体がフォームの一部だから、
childrenでstepForm受け取るんじゃなくて、stepFormをimportしてつかったほうがいいんじゃない？

2021-05-21 06:43 UTC, dubianhaozhi commented on components/roadmaps/step/StepForm.tsx
> +import { LibraryInfo, StepInfo } from '~/server/types'
このStepInfoつかってないから消そうず。

2021-05-21 06:43 UTC, dubianhaozhi commented on components/roadmaps/step/StepForm.tsx
> +      console.log('create:', library)
無駄なconsole消そうず

2021-05-21 06:43 UTC, dubianhaozhi commented on components/roadmaps/step/StepForm.tsx
> +    console.log({ ...data })
無駄なconsole消そうず

2021-05-21 06:43 UTC, dubianhaozhi commented on components/roadmaps/goal/GoalForm.tsx
> +import RHFInput from '~/components/parts/RHFInput'
このRHTInput使ってないから消そうず

2021-05-21 06:43 UTC, dubianhaozhi commented on pages/roadmaps/create.tsx
> +    formState: { errors }
errors使ってなかったら消そうず

2021-05-21 06:43 UTC, dubianhaozhi commented on pages/roadmaps/create.tsx
> +    // console.log({ ...data, steps })
いらないconsoleといらないコメント消そうず

2021-05-21 06:43 UTC, dubianhaozhi commented on pages/roadmaps/create.tsx
> +          register={(register as unknown) as UseFormRegister<FieldValues>}
ここらへんに点在してるunknownってなんだっけ？

2021-05-21 14:43 UTC, dubianhaozhi approved these changes
LGTM

2021-05-21 14:47 UTC, pahalce commented on components/roadmaps/step/OpenStepForm.tsx
> +  children: React.ReactNode
Props増えるのいやでこうしたんだけど直したほうがいい？
OpenStepFormって名前がよくなかったかもしれん
このコンポーネント自体押したらチルドレン開くってだけしか情報持たないし汎用性あるかなと思って

2021-05-21 14:50 UTC, dubianhaozhi commented on components/roadmaps/step/OpenStepForm.tsx
> +  children: React.ReactNode
汎用性あるなら、その機能通りの名前にした方がいいね🙆‍♂️

2021-05-21 23:45 UTC, pahalce commented on pages/roadmaps/create.tsx
> +          register={(register as unknown) as UseFormRegister<FieldValues>}
UseFormでフォームの形式をtypeで指定したらFieldValuesと互換性がないっておこられてたやつ

2021-05-21 23:46 UTC, pahalce commented on pages/roadmaps/create.tsx
> +          register={(register as unknown) as UseFormRegister<FieldValues>}
なおしかたがわからないこれ

2021-05-24 14:17 UTC, dubianhaozhi approved these changes
LGTM

2021-05-24 14:19 UTC, merged