Taira/edit roadmap
Piko-Piko-Pon-Taro/navict-app pull request #163
Opened 2021-05-30 15:05 UTC by pahalce

#87 #160

2021-05-30 23:36 UTC, pahalce commented on components/roadmaps/Roadmap.tsx
> +            token={auth.token}
propsとしてtoken渡さない方がいいか

2021-06-05 12:30 UTC, dubianhaozhi requested changes

2021-06-05 12:30 UTC, dubianhaozhi commented on components/header/Nav.tsx
> +            <Link href="/roadmaps/create">
newにして

2021-06-05 12:30 UTC, dubianhaozhi commented on components/roadmaps/RoadmapComp.tsx
> +/*
`RoadmapComp.tsx`じゃなくて`RoadmapForm.tsx`とかのj方がいいかも
(全体像見えてないので、`RoadmapForm.tsx`は適した名前じゃないかも)

2021-06-05 12:39 UTC, dubianhaozhi approved these changes
LGTM

2021-06-05 12:42 UTC, merged