Feature/watanabe/add process when not logged in
Piko-Piko-Pon-Taro/navict-app pull request #168
Opened 2021-06-05 13:11 UTC by dubianhaozhi

#99

2021-06-07 09:26 UTC, pahalce requested changes

2021-06-07 09:26 UTC, pahalce commented on components/list/RoadmapCard.tsx
> +  isLoggedIn: boolean
これ直接authContextからstateとってきた方がいい気がする

2021-06-07 09:26 UTC, pahalce commented on components/roadmaps/RoadmapForm.tsx
> +  if (!auth?.user) {
AuthContextのisLoggedInとuser両方あるのどうするの前どっちでもよくねって俺が言っちゃった気がするけど、やっぱ統一したほうがいいね

2021-06-07 09:26 UTC, pahalce commented on pages/index.tsx
> +  isLoggedIn: boolean
これもおなじくContextからちょくでとってくる

2021-06-07 09:26 UTC, pahalce commented on pages/index.tsx
> +  isLoggedIn,
おなじく

2021-06-07 09:26 UTC, pahalce commented on pages/index.tsx
> +      <div className={`${auth?.user && 'mb-52'}`}>
これなんだっけ

2021-06-07 09:26 UTC, pahalce commented on pages/index.tsx
> +          isLoggedIn={!!auth?.user}
混在してるから直したいってやつ

2021-06-07 09:26 UTC, pahalce commented on pages/mypage.tsx
> +  if (!auth?.user) {
混在

2021-06-07 09:26 UTC, pahalce commented on pages/roadmaps/[roadmapId].tsx
> +  isLoggedIn: boolean
AuthContextから直のやつ

2021-06-07 09:26 UTC, pahalce commented on pages/roadmaps/new.tsx
> +  if (!auth?.user) {
混在

2021-06-07 09:26 UTC, pahalce commented on pages/signin.tsx
> +    if (typeof prevUrl === 'string') {
これなんだっけ

2021-06-07 09:26 UTC, pahalce commented on pages/users/[userId].tsx
> +  isLoggedIn: boolean
Contextから直

2021-06-07 12:26 UTC, dubianhaozhi commented on components/list/RoadmapCard.tsx
> +  isLoggedIn: boolean
まちがえました。

2021-06-07 12:26 UTC, dubianhaozhi commented on components/roadmaps/RoadmapForm.tsx
> +  if (!auth?.user) {
これは意味的にisLoggedInの方がいいよ

2021-06-07 12:27 UTC, dubianhaozhi commented on pages/index.tsx
> +  isLoggedIn,
おなじことかくな

2021-06-07 12:28 UTC, dubianhaozhi commented on pages/index.tsx
> +      <div className={`${auth?.user && 'mb-52'}`}>
マージン入れてるだけ

2021-06-08 00:58 UTC, pahalce commented on pages/index.tsx
> +      <div className={`${auth?.user && 'mb-52'}`}>
L103ってこんな書き方できるの？
俺いつも三項定理で書いちゃってたわ

2021-06-08 01:01 UTC, pahalce requested changes

2021-06-08 01:01 UTC, pahalce commented on pages/signin.tsx
> +    if (typeof prevUrl === 'string') {
prevUrlがstringってどういう意味？

2021-06-08 03:28 UTC, dubianhaozhi commented on pages/index.tsx
> +      <div className={`${auth?.user && 'mb-52'}`}>
`A && B`
は
Aがtrue, Bがtrue のとき Bを返す
Aがtrue, Bがfalse のとき Bを返す
Aがfalse, Bがtrue のとき Aを返す
Aがfalse, Bがtrue のとき Aを返す
っていう意味なんだけど、

今回ので言うと、
`auth?.user && 'mb-52'`
は
ログインしてたら 'mb-52' を返す
ログインしてなかったら false を返す
なので、バグりはしないけどfalseっていうクラスがついちゃうので変ですね。
直します。

2021-06-08 03:32 UTC, dubianhaozhi commented on pages/index.tsx
> +      <div className={`${auth?.user && 'mb-52'}`}>
クラスに使うとこんな感じで`undefined`になっちゃってたわ。
<img width="278" alt="スクリーンショット 2021-06-08 12 31 58" src="https://user-images.githubusercontent.com/42288506/121118847-87242380-c855-11eb-9116-dfad020cac6d.png">

2021-06-08 03:38 UTC, dubianhaozhi commented on pages/signin.tsx
> +    if (typeof prevUrl === 'string') {
router.queryから取ってくるとstring以外の型になる可能性もあるので。ってやつ
<img width="463" alt="スクリーンショット 2021-06-08 12 36 53" src="https://user-images.githubusercontent.com/42288506/121119222-37922780-c856-11eb-949d-67092b583228.png">

2021-06-08 03:50 UTC, pahalce requested changes

2021-06-08 03:50 UTC, pahalce commented on pages/signin.tsx
> +    if (typeof prevUrl === 'string') {
これabc/[hoge].tsxみたいなファイルに対してabc/a/b/cってurlだとhogeが[a,b,c]って感じにstring[]になるって話だった気がするから、今後そういう構成採用したときにそこに戻れなくならない？

2021-06-08 03:50 UTC, pahalce commented on pages/signin.tsx
> +    if (typeof prevUrl === 'string') {
undefinedの時だけ/にpushするようにしないといけない気がする

2021-06-08 03:50 UTC, pahalce commented on components/roadmaps/RoadmapForm.tsx
> +  if (!auth?.user) {
混在してる奴はAuthContextのnullチェックしなくていいようにする方で対応するわ

2021-06-08 03:57 UTC, dubianhaozhi commented on pages/signin.tsx
> +    if (typeof prevUrl === 'string') {
> これabc/[hoge].tsxみたいなファイルに対してabc/a/b/cってurlだとhogeが[a,b,c]って感じにstring[]になるって話だった気がするから、今後そういう構成採用したときにそこに戻れなくならない？

いや、prevUrlはqueryだから関係ない。
queryは`https://www.google.com/index.html?prevUrl=/aaa/sss`
みたいな感じ。
`const { prevUrl } = router.query`でとると、`/aaa/sss`っていうstringになるはず。

2021-06-08 03:58 UTC, dubianhaozhi commented on components/roadmaps/RoadmapForm.tsx
> +  if (!auth?.user) {
はい。

2021-06-08 04:38 UTC, pahalce commented on pages/index.tsx
> +      <div className={`${auth?.user && 'mb-52'}`}>
なるほどね

2021-06-09 14:22 UTC, pahalce commented on pages/signin.tsx
> +    if (typeof prevUrl === 'string') {
いつstring[]になるのかな

2021-06-09 14:22 UTC, pahalce commented on pages/signin.tsx
> +    if (typeof prevUrl === 'string') {
クエリ複数個あったときな気がする
クエリ複数あるページ見てる状態からログインしたらそこに戻れなくなるってことじゃない？

2021-06-09 14:29 UTC, pahalce approved these changes
LGTM

2021-06-09 14:40 UTC, pahalce approved these changes
LGTM

2021-06-09 14:43 UTC, merged