Taira/header token
Piko-Piko-Pon-Taro/navict-app pull request #179
Opened 2021-06-11 03:34 UTC by pahalce

#164 #76 
ついでにマイページのライクの挙動直した

2021-06-11 09:55 UTC, dubianhaozhi requested changes
やっぱRoadmapCard.tsxでlikeのstate管理した方がいいや
likeするたびにrevalidateするとたくさんでーたとってくることになっちゃうからそういう実装にしたんだった。

2021-06-11 09:55 UTC, dubianhaozhi commented on pages/users/[userId].tsx
> +    revalidate()
revalidateしなくていいや

2021-06-11 09:55 UTC, dubianhaozhi commented on pages/index.tsx
> +    revalidate()
revalidateしなくていいや

2021-06-11 09:55 UTC, dubianhaozhi commented on components/list/RoadmapCard.tsx
> -  const [isLiked, setIsliked] = useState<boolean>(initialIsLiked)
ごめんこれやっぱいるわ

2021-06-15 02:45 UTC, pahalce commented
ライクの挙動直したってやつこの実装だとリクエスト数増えたりしてよくないからいったんもとに戻した

2021-06-15 09:48 UTC, dubianhaozhi approved these changes
LGTM

2021-06-15 11:01 UTC, merged